version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongo-docker
    network_mode: host

  configserver:
    image: configserverapp
    build: configserver/
    restart: always
    network_mode: host
    container_name: configserver-docker
    ports:
      - "8888:8888"
    expose:
      - "8888"

  eureka:
    image: eurekaapp
    build: eurekaservice/
    restart: always
    network_mode: host
    container_name: eureka-docker
    ports:
      - "8761:8761"
    expose:
      - "8761"

  zuul:
    image: zuulapp
    build: micro-service-zulu/
    restart: always
    network_mode: host
    container_name: zuul-docker
    ports:
      - "8097:8097"
    expose:
      - "8097"

  trackservice:
    image: trackapp
    build: MuzixApplicationMongodTrack/
    restart: always
    network_mode: host
    container_name: track-docker
    depends_on:
      - mongo
    ports:
      - "8096:8096"
    expose:
      - "8096"

  userservice:
    image: userapp
    build: MuzixApplicationMongodUser/
    restart: always
    network_mode: host
    container_name: user-docker
    depends_on:
      - mongo
    ports:
      - "8095:8095"
    expose:
      - "8095"